celebrities = [
    {"name": "Cristiano Ronaldo", "followers": 625, "country": "Portugal", "profession": "Footballer"},
    {"name": "Lionel Messi", "followers": 500, "country": "Argentina", "profession": "Footballer"},
    {"name": "Selena Gomez", "followers": 430, "country": "USA", "profession": "Singer, Actress"},
    {"name": "Kylie Jenner", "followers": 400, "country": "USA", "profession": "Businesswoman, Influencer"},
    {"name": "Dwayne Johnson", "followers": 390, "country": "USA", "profession": "Actor, Former Wrestler"},
    {"name": "Ariana Grande", "followers": 380, "country": "USA", "profession": "Singer, Actress"},
    {"name": "Kim Kardashian", "followers": 360, "country": "USA", "profession": "Businesswoman, Influencer"},
    {"name": "Beyoncé", "followers": 320, "country": "USA", "profession": "Singer"},
    {"name": "Khloé Kardashian", "followers": 310, "country": "USA", "profession": "Businesswoman, Influencer"},
    {"name": "Kendall Jenner", "followers": 290, "country": "USA", "profession": "Model, Influencer"},
    {"name": "Justin Bieber", "followers": 280, "country": "Canada", "profession": "Singer"},
    {"name": "Taylor Swift", "followers": 270, "country": "USA", "profession": "Singer"},
    {"name": "Jennifer Lopez", "followers": 250, "country": "USA", "profession": "Singer, Actress"},
    {"name": "Nicki Minaj", "followers": 220, "country": "USA", "profession": "Rapper"},
    {"name": "Neymar Jr", "followers": 215, "country": "Brazil", "profession": "Footballer"},
    {"name": "Miley Cyrus", "followers": 210, "country": "USA", "profession": "Singer, Actress"},
    {"name": "Kourtney Kardashian", "followers": 200, "country": "USA", "profession": "Businesswoman, Influencer"},
    {"name": "Kevin Hart", "followers": 195, "country": "USA", "profession": "Comedian, Actor"},
    {"name": "Zendaya", "followers": 180, "country": "USA", "profession": "Actress, Singer"},
    {"name": "Virat Kohli", "followers": 175, "country": "India", "profession": "Cricketer"},
    {"name": "Shakira", "followers": 170, "country": "Colombia", "profession": "Singer"},
    {"name": "Billie Eilish", "followers": 160, "country": "USA", "profession": "Singer"},
    {"name": "Emma Watson", "followers": 155, "country": "UK", "profession": "Actress"},
    {"name": "LeBron James", "followers": 150, "country": "USA", "profession": "Basketball Player"},
    {"name": "Gigi Hadid", "followers": 145, "country": "USA", "profession": "Model"},
    {"name": "Chris Hemsworth", "followers": 140, "country": "Australia", "profession": "Actor"},
    {"name": "Robert Downey Jr.", "followers": 135, "country": "USA", "profession": "Actor"},
    {"name": "Cardi B", "followers": 130, "country": "USA", "profession": "Rapper"},
    {"name": "Drake", "followers": 125, "country": "Canada", "profession": "Rapper"},
    {"name": "Tom Holland", "followers": 120, "country": "UK", "profession": "Actor"},
    {"name": "Shawn Mendes", "followers": 115, "country": "Canada", "profession": "Singer"},
    {"name": "Priyanka Chopra", "followers": 110, "country": "India", "profession": "Actress, Singer"},
    {"name": "Hugh Jackman", "followers": 105, "country": "Australia", "profession": "Actor"},
    {"name": "Gal Gadot", "followers": 100, "country": "Israel", "profession": "Actress"},
    {"name": "Jason Momoa", "followers": 98, "country": "USA", "profession": "Actor"},
    {"name": "Ed Sheeran", "followers": 95, "country": "UK", "profession": "Singer"},
    {"name": "Dua Lipa", "followers": 92, "country": "UK", "profession": "Singer"},
    {"name": "Will Smith", "followers": 90, "country": "USA", "profession": "Actor"},
    {"name": "Zac Efron", "followers": 87, "country": "USA", "profession": "Actor"},
    {"name": "Camila Cabello", "followers": 85, "country": "Cuba", "profession": "Singer"},
    {"name": "Post Malone", "followers": 82, "country": "USA", "profession": "Singer"},
    {"name": "Bruno Mars", "followers": 80, "country": "USA", "profession": "Singer"},
    {"name": "Margot Robbie", "followers": 78, "country": "Australia", "profession": "Actress"},
    {"name": "Keanu Reeves", "followers": 75, "country": "Canada", "profession": "Actor"},
    {"name": "Harry Styles", "followers": 72, "country": "UK", "profession": "Singer"},
    {"name": "Timothée Chalamet", "followers": 70, "country": "USA", "profession": "Actor"},
    {"name": "Ryan Reynolds", "followers": 68, "country": "Canada", "profession": "Actor"},
    {"name": "Vin Diesel", "followers": 65, "country": "USA", "profession": "Actor"},
    {"name": "Jackie Chan", "followers": 62, "country": "Hong Kong", "profession": "Actor, Martial Artist"},
    {"name": "Anya Taylor-Joy", "followers": 60, "country": "USA", "profession": "Actress"},
    {"name": "Chris Evans", "followers": 58, "country": "USA", "profession": "Actor"},
    {"name": "Jennifer Aniston", "followers": 55, "country": "USA", "profession": "Actress"},
    {"name": "Emma Stone", "followers": 52, "country": "USA", "profession": "Actress"},
    {"name": "Millie Bobby Brown", "followers": 50, "country": "UK", "profession": "Actress"},
]